server:
  port: 8888 #项目端口
  servlet:
    context-path: / #项目名称（上下文）
#    session:
#      timeout: 30m #session的生命周期
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
  devtools:
    livereload:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: ownDataSource
    url: jdbc:mysql://127.0.0.1:3306/bilibili
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  #应用配置
  application:
    name: bilibili
  main:
    allow-bean-definition-overriding: true #springboot默认false，不支持相同的bean被覆盖
#mybatis-plus自动生成代码的配置
mybatis-plus:
  type-aliases-package: org.ruaho.entity
  type-enums-package: org.ruaho.entity.enums
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler #枚举数据转换
#日志配置
logging:
  level:
    root: INFO #日志级别：trace<debugger<info<warn<error<fatal (springboot 默认info级别)
  file:
    path: /Users/liuyuxuan/IdeaProjects/log #日志存储路径
    max-history: 3 #日志文件保存时间
    max-size: 2000 #日志文件最大容量